{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Bind",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "Queries per minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_resolver_queries_total{type=\"NS\"}",
     "legendFormat": "Bind Transliations"
    }
   ]
  },
  {
   "title": "CPU load VM-1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu{instance=\"vm-1.nuttn.go.:9100\", mode=\"user\"}[1m])"
    }
   ]
  },
  {
   "title": "CPU load VM-1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu{instance=\"vm-1.nuttn.go.:9100\", mode=\"user\"}[1m])"
    }
   ]
  },
  {
   "title": "mysql",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Queries per minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_global_status_queries", "legendFormat": "mysql queries" }
   ]
  },
  {
   "title": "Memory load VM-1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal{instance=\"vm-1.nuttn.go.:9100\"} - node_memory_MemAvailable{instance=\"vm-1.nuttn.go.:9100\"})/node_memory_MemTotal{instance=\"vm-1.nuttn.go.:9100\"}"
    }
   ]
  },
  {
   "title": "Memory load VM-2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal{instance=\"vm-2.nuttn.go.:9100\"} - node_memory_MemAvailable{instance=\"vm-2.nuttn.go.:9100\"})/node_memory_MemTotal{instance=\"vm-2.nuttn.go.:9100\"}"
    }
   ]
  },
  {
   "title": "nginx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "Nginx requests" }
   ]
  },
  {
   "title": "Latency Mean",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}